// Generated by gencpp from file servo/servo_order.msg
// DO NOT EDIT!


#ifndef SERVO_MESSAGE_SERVO_ORDER_H
#define SERVO_MESSAGE_SERVO_ORDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo
{
template <class ContainerAllocator>
struct servo_order_
{
  typedef servo_order_<ContainerAllocator> Type;

  servo_order_()
    : numeroMoteur(0)
    , position(0.0)  {
    }
  servo_order_(const ContainerAllocator& _alloc)
    : numeroMoteur(0)
    , position(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _numeroMoteur_type;
  _numeroMoteur_type numeroMoteur;

   typedef float _position_type;
  _position_type position;




  typedef boost::shared_ptr< ::servo::servo_order_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo::servo_order_<ContainerAllocator> const> ConstPtr;

}; // struct servo_order_

typedef ::servo::servo_order_<std::allocator<void> > servo_order;

typedef boost::shared_ptr< ::servo::servo_order > servo_orderPtr;
typedef boost::shared_ptr< ::servo::servo_order const> servo_orderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo::servo_order_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo::servo_order_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'servo': ['/home/arpad/catkin_ws/src/servo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo::servo_order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo::servo_order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo::servo_order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo::servo_order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo::servo_order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo::servo_order_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo::servo_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8d0c7e8a697e8acacd6bb6f954ac448";
  }

  static const char* value(const ::servo::servo_order_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8d0c7e8a697e8acULL;
  static const uint64_t static_value2 = 0xacd6bb6f954ac448ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo::servo_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo/servo_order";
  }

  static const char* value(const ::servo::servo_order_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo::servo_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 numeroMoteur\n\
float32 position\n\
";
  }

  static const char* value(const ::servo::servo_order_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo::servo_order_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numeroMoteur);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct servo_order_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo::servo_order_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo::servo_order_<ContainerAllocator>& v)
  {
    s << indent << "numeroMoteur: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numeroMoteur);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_MESSAGE_SERVO_ORDER_H
